name: Check format

on:
  push:
    branches:
      - clang-format
  pull_request:
    branches:
      - clang-format

jobs:
  check-format:
    runs-on: fedora
    steps:
      - uses: actions/checkout@v4
      - name: Check format
        run: make check-format
